name: CI

on: [push]

jobs:
  build:
    services:
      photoprism:
        image: thielepaul/photoprism:db-api-demo
        ports:
          - 2342:2342
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - run: sudo apt install libsqlite3-dev
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.0.0
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed lib
      - run: flutter packages pub run build_runner build
      - run: flutter analyze --pub
      - run: flutter test --coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
      - env:
          KEY_JKS: ${{ secrets.KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: echo "$KEY_JKS" | base64 -d > key.jks && flutter build apk --pub --flavor prod --no-shrink
      - uses: actions/upload-artifact@v1
        with:
          name: photoprism-apk
          path: build/app/outputs/apk/prod/release/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: photoprism-apk
      - run: mv photoprism-apk/app-prod-release.apk photoprism.apk
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-db-api"
          prerelease: true
          title: "Development CI Build (DB API)"
          files: photoprism.apk
