name: Pull Request CI

on: [pull_request]

jobs:
  build:
    services:
      photoprism:
        image: thielepaul/photoprism:db-api-demo
        ports:
          - 2342:2342
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt install libsqlite3-dev
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.0.0
      - run: flutter pub get
      - run: flutter format --dry-run --set-exit-if-changed lib
      - run: flutter packages pub run build_runner build
      - run: flutter analyze --pub
      - run: flutter test --coverage
      - run: flutter build apk --pub --profile --flavor dev --no-shrink
      - uses: actions/upload-artifact@v1
        with:
          name: photoprism-apk
          path: build/app/outputs/apk/dev/profile/
